import fs from 'node:fs'
import path from 'node:path'
import { scanPlates } from './scan-plates.ts'

export function writeGeneratedCatalog(repoRoot: string, webRoot: string) {
  const catalog = scanPlates(repoRoot)
  const outDir = path.join(webRoot, 'src', 'generated')
  fs.mkdirSync(outDir, { recursive: true })
  const outPath = path.join(outDir, 'catalog.ts')
  const source = `/* Generated by the Plate Hub Vite plugin. Do not edit. */\nimport type { Catalog } from '../types'\n\nexport const catalog: Catalog = ${JSON.stringify(catalog, null, 2)}\n`
  const fingerprint = (text: string) => text.replace(/"generatedAt": "[^"]*"/g, '')
  if (fs.existsSync(outPath) && fingerprint(fs.readFileSync(outPath, 'utf8')) === fingerprint(source)) {
    return catalog
  }
  fs.writeFileSync(outPath, source)
  return catalog
}
